import { storage } from "./storage";

const destinationsData = [
  // FEATURED DESTINATIONS
  {
    name: "Goa",
    state: "Goa",
    shortDescription: "Golden beaches, Portuguese heritage, and vibrant nightlife",
    imageUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800",
    bestSeason: "November to March",
    isFeatured: true,
    featuredDate: new Date(),
  },
  {
    name: "Kerala",
    state: "Kerala",
    shortDescription: "God's Own Country with serene backwaters and lush tea estates",
    imageUrl: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
    bestSeason: "October to March",
    isFeatured: true,
    featuredDate: new Date(),
  },
  {
    name: "Jaipur",
    state: "Rajasthan",
    shortDescription: "The Pink City featuring magnificent forts and palaces",
    imageUrl: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800",
    bestSeason: "October to March",
    isFeatured: true,
    featuredDate: new Date(),
  },
  
  // ANDHRA PRADESH
  { name: "Hyderabad", state: "Telangana", shortDescription: "City of Pearls with historic monuments and biryani" },
  { name: "Visakhapatnam", state: "Andhra Pradesh", shortDescription: "Port city with beautiful beaches and hills" },
  { name: "Vijayawada", state: "Andhra Pradesh", shortDescription: "Cultural hub on the banks of Krishna River" },
  { name: "Tirupati", state: "Andhra Pradesh", shortDescription: "Famous pilgrimage destination with Sri Venkateswara Temple" },
  { name: "Guntur", state: "Andhra Pradesh", shortDescription: "Historic city known for chili trade" },
  { name: "Nellore", state: "Andhra Pradesh", shortDescription: "Ancient town with temples and beaches" },
  { name: "Kurnool", state: "Andhra Pradesh", shortDescription: "Gateway to Belum Caves" },
  { name: "Rajahmundry", state: "Andhra Pradesh", shortDescription: "Cultural capital on Godavari banks" },
  { name: "Kakinada", state: "Andhra Pradesh", shortDescription: "Beach town with Hope Island" },
  { name: "Anantapur", state: "Andhra Pradesh", shortDescription: "Historic town with Lepakshi Temple nearby" },
  { name: "Kadapa", state: "Andhra Pradesh", shortDescription: "Known for religious sites and mining" },
  { name: "Srikakulam", state: "Andhra Pradesh", shortDescription: "Temple town with ancient heritage" },
  { name: "Eluru", state: "Andhra Pradesh", shortDescription: "Known for carpets and handlooms" },
  { name: "Ongole", state: "Andhra Pradesh", shortDescription: "Famous for Ongole cattle breed" },
  { name: "Chittoor", state: "Andhra Pradesh", shortDescription: "Gateway to Tirumala hills" },
  { name: "Machilipatnam", state: "Andhra Pradesh", shortDescription: "Historic port with Kalamkari art" },
  { name: "Tenali", state: "Andhra Pradesh", shortDescription: "Rice bowl of Andhra Pradesh" },
  { name: "Proddatur", state: "Andhra Pradesh", shortDescription: "Historic town with temples" },
  
  // ARUNACHAL PRADESH
  { name: "Itanagar", state: "Arunachal Pradesh", shortDescription: "Capital city with Ita Fort ruins" },
  { name: "Tawang", state: "Arunachal Pradesh", shortDescription: "Buddhist monastery town near Tibet border" },
  { name: "Ziro", state: "Arunachal Pradesh", shortDescription: "UNESCO heritage site with Apatani tribe" },
  { name: "Pasighat", state: "Arunachal Pradesh", shortDescription: "Oldest town with Siang River" },
  { name: "Bomdila", state: "Arunachal Pradesh", shortDescription: "Hill station with Buddhist monasteries" },
  { name: "Along", state: "Arunachal Pradesh", shortDescription: "Tribal town with hanging bridges" },
  { name: "Tezu", state: "Arunachal Pradesh", shortDescription: "Gateway to Glow Lake" },
  { name: "Naharlagun", state: "Arunachal Pradesh", shortDescription: "Twin city of Itanagar" },
  
  // ASSAM
  { name: "Guwahati", state: "Assam", shortDescription: "Gateway to Northeast India with Kamakhya Temple" },
  { name: "Jorhat", state: "Assam", shortDescription: "Tea capital with Majuli Island nearby" },
  { name: "Dibrugarh", state: "Assam", shortDescription: "Tea city of Assam" },
  { name: "Silchar", state: "Assam", shortDescription: "Gateway to Barak Valley" },
  { name: "Tezpur", state: "Assam", shortDescription: "Cultural capital with scenic beauty" },
  { name: "Nagaon", state: "Assam", shortDescription: "Historic town with Kaziranga nearby" },
  { name: "Tinsukia", state: "Assam", shortDescription: "Gateway to Dibru-Saikhowa" },
  { name: "Bongaigaon", state: "Assam", shortDescription: "Industrial town with Manas nearby" },
  { name: "Sibsagar", state: "Assam", shortDescription: "Ahom dynasty capital with heritage sites" },
  { name: "Majuli", state: "Assam", shortDescription: "World's largest river island" },
  { name: "Kaziranga", state: "Assam", shortDescription: "UNESCO site famous for one-horned rhinos" },
  
  // BIHAR
  { name: "Patna", state: "Bihar", shortDescription: "Ancient capital on the Ganges with rich history" },
  { name: "Gaya", state: "Bihar", shortDescription: "Sacred city with Bodh Gaya nearby" },
  { name: "Bodh Gaya", state: "Bihar", shortDescription: "Where Buddha attained enlightenment" },
  { name: "Muzaffarpur", state: "Bihar", shortDescription: "Known for litchis and education" },
  { name: "Bhagalpur", state: "Bihar", shortDescription: "Silk city on the Ganges" },
  { name: "Darbhanga", state: "Bihar", shortDescription: "Cultural hub of Mithila region" },
  { name: "Purnia", state: "Bihar", shortDescription: "Gateway to Nepal border" },
  { name: "Nalanda", state: "Bihar", shortDescription: "Ancient university ruins UNESCO site" },
  { name: "Rajgir", state: "Bihar", shortDescription: "Ancient city with hot springs" },
  { name: "Sasaram", state: "Bihar", shortDescription: "Tomb of Sher Shah Suri" },
  { name: "Vaishali", state: "Bihar", shortDescription: "Ancient republic and Buddhist site" },
  
  // CHHATTISGARH
  { name: "Raipur", state: "Chhattisgarh", shortDescription: "Capital city with lakes and temples" },
  { name: "Bhilai", state: "Chhattisgarh", shortDescription: "Steel city of India" },
  { name: "Bilaspur", state: "Chhattisgarh", shortDescription: "Judicial capital with Achanakmar" },
  { name: "Korba", state: "Chhattisgarh", shortDescription: "Power capital of Chhattisgarh" },
  { name: "Durg", state: "Chhattisgarh", shortDescription: "Industrial hub with ancient temples" },
  { name: "Jagdalpur", state: "Chhattisgarh", shortDescription: "Gateway to Chitrakote Falls" },
  { name: "Raigarh", state: "Chhattisgarh", shortDescription: "Cultural capital with music tradition" },
  { name: "Ambikapur", state: "Chhattisgarh", shortDescription: "Cleanest city with tribal culture" },
  { name: "Chitrakote", state: "Chhattisgarh", shortDescription: "Niagara Falls of India" },
  
  // GOA
  { name: "Panaji", state: "Goa", shortDescription: "Capital city with Portuguese architecture" },
  { name: "Margao", state: "Goa", shortDescription: "Commercial hub of South Goa" },
  { name: "Vasco da Gama", state: "Goa", shortDescription: "Port city with Mormugao harbor" },
  { name: "Mapusa", state: "Goa", shortDescription: "Friday market town in North Goa" },
  { name: "Ponda", state: "Goa", shortDescription: "Temple town with spice plantations" },
  { name: "Calangute", state: "Goa", shortDescription: "Queen of beaches" },
  { name: "Baga", state: "Goa", shortDescription: "Party beach destination" },
  { name: "Anjuna", state: "Goa", shortDescription: "Famous flea market and nightlife" },
  { name: "Candolim", state: "Goa", shortDescription: "Serene beach with water sports" },
  { name: "Palolem", state: "Goa", shortDescription: "Crescent shaped beach paradise" },
  { name: "Arambol", state: "Goa", shortDescription: "Hippie beach with sweet water lake" },
  { name: "Vagator", state: "Goa", shortDescription: "Cliff beach with Chapora Fort" },
  { name: "Morjim", state: "Goa", shortDescription: "Turtle nesting beach" },
  { name: "Colva", state: "Goa", shortDescription: "Popular beach in South Goa" },
  { name: "Old Goa", state: "Goa", shortDescription: "UNESCO churches and cathedrals" },
  
  // GUJARAT
  { name: "Ahmedabad", state: "Gujarat", shortDescription: "UNESCO heritage city with rich textile history" },
  { name: "Surat", state: "Gujarat", shortDescription: "Diamond city and textile hub" },
  { name: "Vadodara", state: "Gujarat", shortDescription: "Cultural capital with Laxmi Vilas Palace" },
  { name: "Rajkot", state: "Gujarat", shortDescription: "City associated with Mahatma Gandhi" },
  { name: "Bhavnagar", state: "Gujarat", shortDescription: "Gateway to Palitana temples" },
  { name: "Jamnagar", state: "Gujarat", shortDescription: "Jewel of Kathiawad with marine park" },
  { name: "Junagadh", state: "Gujarat", shortDescription: "Historic city with Gir Forest nearby" },
  { name: "Gandhinagar", state: "Gujarat", shortDescription: "Planned capital with Akshardham" },
  { name: "Kutch", state: "Gujarat", shortDescription: "Rann of Kutch white desert" },
  { name: "Dwarka", state: "Gujarat", shortDescription: "Sacred pilgrimage on Arabian Sea" },
  { name: "Somnath", state: "Gujarat", shortDescription: "Ancient Jyotirlinga temple" },
  { name: "Gir", state: "Gujarat", shortDescription: "Only home of Asiatic lions" },
  { name: "Diu", state: "Gujarat", shortDescription: "Beach destination with Portuguese heritage" },
  { name: "Saputara", state: "Gujarat", shortDescription: "Only hill station in Gujarat" },
  { name: "Statue of Unity", state: "Gujarat", shortDescription: "World's tallest statue" },
  { name: "Porbandar", state: "Gujarat", shortDescription: "Birthplace of Mahatma Gandhi" },
  { name: "Bhuj", state: "Gujarat", shortDescription: "Gateway to Rann of Kutch" },
  { name: "Palitana", state: "Gujarat", shortDescription: "City of temples on Shatrunjaya hill" },
  { name: "Modhera", state: "Gujarat", shortDescription: "Famous Sun Temple" },
  { name: "Patan", state: "Gujarat", shortDescription: "UNESCO Rani ki Vav stepwell" },
  
  // HARYANA
  { name: "Gurugram", state: "Haryana", shortDescription: "Millennium City and IT hub" },
  { name: "Faridabad", state: "Haryana", shortDescription: "Industrial city near Delhi" },
  { name: "Chandigarh", state: "Haryana", shortDescription: "Planned city capital shared with Punjab" },
  { name: "Panipat", state: "Haryana", shortDescription: "City of weavers and historic battles" },
  { name: "Ambala", state: "Haryana", shortDescription: "Gateway to Himachal Pradesh" },
  { name: "Karnal", state: "Haryana", shortDescription: "Rice bowl of India" },
  { name: "Hisar", state: "Haryana", shortDescription: "Steel city with ancient ruins" },
  { name: "Rohtak", state: "Haryana", shortDescription: "Heart of Haryana" },
  { name: "Sonipat", state: "Haryana", shortDescription: "Industrial hub near NCR" },
  { name: "Kurukshetra", state: "Haryana", shortDescription: "Land of Mahabharata war" },
  { name: "Panchkula", state: "Haryana", shortDescription: "Planned city with Morni Hills" },
  { name: "Yamunanagar", state: "Haryana", shortDescription: "Paper industry hub" },
  
  // HIMACHAL PRADESH
  { name: "Shimla", state: "Himachal Pradesh", shortDescription: "Queen of Hills and former summer capital" },
  { name: "Manali", state: "Himachal Pradesh", shortDescription: "Adventure capital with snow-capped peaks" },
  { name: "Dharamshala", state: "Himachal Pradesh", shortDescription: "Home of Dalai Lama and McLeodganj" },
  { name: "Kullu", state: "Himachal Pradesh", shortDescription: "Valley of Gods with Dussehra festival" },
  { name: "Dalhousie", state: "Himachal Pradesh", shortDescription: "Colonial hill station with pine forests" },
  { name: "Kasol", state: "Himachal Pradesh", shortDescription: "Mini Israel of India in Parvati Valley" },
  { name: "Spiti Valley", state: "Himachal Pradesh", shortDescription: "Cold desert mountain valley" },
  { name: "Bir Billing", state: "Himachal Pradesh", shortDescription: "Paragliding capital of India" },
  { name: "Chamba", state: "Himachal Pradesh", shortDescription: "Ancient kingdom with temples" },
  { name: "Kangra", state: "Himachal Pradesh", shortDescription: "Valley known for paintings and tea" },
  { name: "Kinnaur", state: "Himachal Pradesh", shortDescription: "Land of fairies and apples" },
  { name: "Khajjiar", state: "Himachal Pradesh", shortDescription: "Mini Switzerland of India" },
  { name: "Mcleodganj", state: "Himachal Pradesh", shortDescription: "Little Lhasa with Tibetan culture" },
  { name: "Kufri", state: "Himachal Pradesh", shortDescription: "Ski resort near Shimla" },
  { name: "Solang Valley", state: "Himachal Pradesh", shortDescription: "Adventure sports hub near Manali" },
  { name: "Rohtang Pass", state: "Himachal Pradesh", shortDescription: "High mountain pass to Lahaul" },
  { name: "Tirthan Valley", state: "Himachal Pradesh", shortDescription: "Offbeat destination with trout fishing" },
  { name: "Jibhi", state: "Himachal Pradesh", shortDescription: "Serene village in Tirthan Valley" },
  { name: "Malana", state: "Himachal Pradesh", shortDescription: "Ancient village with unique culture" },
  
  // JHARKHAND
  { name: "Ranchi", state: "Jharkhand", shortDescription: "City of waterfalls and capital" },
  { name: "Jamshedpur", state: "Jharkhand", shortDescription: "Steel city founded by Tatas" },
  { name: "Dhanbad", state: "Jharkhand", shortDescription: "Coal capital of India" },
  { name: "Bokaro", state: "Jharkhand", shortDescription: "Steel city with Bokaro Steel Plant" },
  { name: "Deoghar", state: "Jharkhand", shortDescription: "Sacred town with Baidyanath Temple" },
  { name: "Hazaribagh", state: "Jharkhand", shortDescription: "Wildlife sanctuary and hill station" },
  { name: "Giridih", state: "Jharkhand", shortDescription: "Known for mica and Jain temples" },
  { name: "Netarhat", state: "Jharkhand", shortDescription: "Queen of Chotanagpur" },
  { name: "Betla", state: "Jharkhand", shortDescription: "National park with tigers" },
  
  // KARNATAKA
  { name: "Bengaluru", state: "Karnataka", shortDescription: "Silicon Valley of India with pleasant weather" },
  { name: "Mysuru", state: "Karnataka", shortDescription: "City of Palaces with Dasara festival" },
  { name: "Mangaluru", state: "Karnataka", shortDescription: "Port city with beautiful beaches" },
  { name: "Hubli", state: "Karnataka", shortDescription: "Commercial capital of North Karnataka" },
  { name: "Belgaum", state: "Karnataka", shortDescription: "Military hub near Western Ghats" },
  { name: "Hampi", state: "Karnataka", shortDescription: "UNESCO site of Vijayanagara Empire" },
  { name: "Coorg", state: "Karnataka", shortDescription: "Scotland of India with coffee estates" },
  { name: "Gokarna", state: "Karnataka", shortDescription: "Beach town with Om Beach" },
  { name: "Udupi", state: "Karnataka", shortDescription: "Temple town famous for cuisine" },
  { name: "Badami", state: "Karnataka", shortDescription: "Cave temples of Chalukyas" },
  { name: "Chikmagalur", state: "Karnataka", shortDescription: "Coffee land with Mullayanagiri peak" },
  { name: "Dandeli", state: "Karnataka", shortDescription: "Adventure hub with river rafting" },
  { name: "Kabini", state: "Karnataka", shortDescription: "Wildlife safari destination" },
  { name: "Bandipur", state: "Karnataka", shortDescription: "Tiger reserve in Nilgiris" },
  { name: "Shivanasamudra", state: "Karnataka", shortDescription: "Segmented waterfall on Kaveri" },
  { name: "Nandi Hills", state: "Karnataka", shortDescription: "Sunrise point near Bangalore" },
  { name: "Bijapur", state: "Karnataka", shortDescription: "Gol Gumbaz and Islamic architecture" },
  { name: "Shravanabelagola", state: "Karnataka", shortDescription: "Jain pilgrimage with Gommateshwara" },
  { name: "Murudeshwar", state: "Karnataka", shortDescription: "Temple with world's second tallest Shiva" },
  { name: "Agumbe", state: "Karnataka", shortDescription: "Cherrapunji of South India" },
  
  // KERALA
  { name: "Thiruvananthapuram", state: "Kerala", shortDescription: "Capital city with Padmanabhaswamy Temple" },
  { name: "Kochi", state: "Kerala", shortDescription: "Queen of Arabian Sea with colonial heritage" },
  { name: "Kozhikode", state: "Kerala", shortDescription: "City of spices where Vasco da Gama landed" },
  { name: "Thrissur", state: "Kerala", shortDescription: "Cultural capital with Pooram festival" },
  { name: "Alleppey", state: "Kerala", shortDescription: "Venice of the East with backwaters" },
  { name: "Munnar", state: "Kerala", shortDescription: "Tea gardens in the clouds" },
  { name: "Thekkady", state: "Kerala", shortDescription: "Periyar Wildlife Sanctuary" },
  { name: "Kovalam", state: "Kerala", shortDescription: "Beach resort with lighthouse" },
  { name: "Varkala", state: "Kerala", shortDescription: "Cliff beach with mineral springs" },
  { name: "Wayanad", state: "Kerala", shortDescription: "Hill district with wildlife and waterfalls" },
  { name: "Kumarakom", state: "Kerala", shortDescription: "Backwater resort destination" },
  { name: "Bekal", state: "Kerala", shortDescription: "Beach fort in North Kerala" },
  { name: "Kannur", state: "Kerala", shortDescription: "Land of looms and lores" },
  { name: "Athirapally", state: "Kerala", shortDescription: "Niagara of India waterfall" },
  { name: "Fort Kochi", state: "Kerala", shortDescription: "Historic quarter with Chinese nets" },
  { name: "Marari", state: "Kerala", shortDescription: "Secluded beach destination" },
  { name: "Vagamon", state: "Kerala", shortDescription: "Hill station with meadows" },
  
  // LADAKH
  { name: "Leh", state: "Ladakh", shortDescription: "High-altitude desert capital with monasteries" },
  { name: "Pangong Lake", state: "Ladakh", shortDescription: "Blue lake extending to Tibet" },
  { name: "Nubra Valley", state: "Ladakh", shortDescription: "Cold desert with Bactrian camels" },
  { name: "Tso Moriri", state: "Ladakh", shortDescription: "High altitude lake in Changthang" },
  { name: "Kargil", state: "Ladakh", shortDescription: "Gateway to Zanskar" },
  { name: "Zanskar", state: "Ladakh", shortDescription: "Remote valley with frozen river trek" },
  { name: "Khardung La", state: "Ladakh", shortDescription: "One of highest motorable passes" },
  { name: "Hemis", state: "Ladakh", shortDescription: "Famous monastery with festival" },
  { name: "Lamayuru", state: "Ladakh", shortDescription: "Moonland landscape monastery" },
  { name: "Diskit", state: "Ladakh", shortDescription: "Monastery with giant Buddha statue" },
  
  // MADHYA PRADESH
  { name: "Bhopal", state: "Madhya Pradesh", shortDescription: "City of Lakes and capital" },
  { name: "Indore", state: "Madhya Pradesh", shortDescription: "Commercial capital and food paradise" },
  { name: "Jabalpur", state: "Madhya Pradesh", shortDescription: "Marble Rocks and Dhuandhar Falls" },
  { name: "Gwalior", state: "Madhya Pradesh", shortDescription: "Fort city with musical heritage" },
  { name: "Ujjain", state: "Madhya Pradesh", shortDescription: "Ancient city of Kumbh Mela" },
  { name: "Khajuraho", state: "Madhya Pradesh", shortDescription: "UNESCO temples with erotic sculptures" },
  { name: "Sanchi", state: "Madhya Pradesh", shortDescription: "UNESCO Buddhist stupas" },
  { name: "Orchha", state: "Madhya Pradesh", shortDescription: "Medieval town with Bundela palaces" },
  { name: "Pachmarhi", state: "Madhya Pradesh", shortDescription: "Queen of Satpura hills" },
  { name: "Kanha", state: "Madhya Pradesh", shortDescription: "Tiger reserve inspiration for Jungle Book" },
  { name: "Bandhavgarh", state: "Madhya Pradesh", shortDescription: "Highest tiger density park" },
  { name: "Pench", state: "Madhya Pradesh", shortDescription: "Tiger reserve on MP-Maharashtra border" },
  { name: "Mandu", state: "Madhya Pradesh", shortDescription: "Romantic ruins of Afghan architecture" },
  { name: "Omkareshwar", state: "Madhya Pradesh", shortDescription: "Om-shaped island Jyotirlinga" },
  { name: "Maheshwar", state: "Madhya Pradesh", shortDescription: "Temple town on Narmada with sarees" },
  { name: "Bhimbetka", state: "Madhya Pradesh", shortDescription: "UNESCO rock shelters with cave paintings" },
  
  // MAHARASHTRA
  { name: "Mumbai", state: "Maharashtra", shortDescription: "City of Dreams and financial capital" },
  { name: "Pune", state: "Maharashtra", shortDescription: "Cultural capital with pleasant climate" },
  { name: "Nagpur", state: "Maharashtra", shortDescription: "Orange city at center of India" },
  { name: "Nashik", state: "Maharashtra", shortDescription: "Wine capital and Kumbh Mela city" },
  { name: "Aurangabad", state: "Maharashtra", shortDescription: "Gateway to Ajanta Ellora caves" },
  { name: "Lonavala", state: "Maharashtra", shortDescription: "Hill station between Mumbai-Pune" },
  { name: "Mahabaleshwar", state: "Maharashtra", shortDescription: "Strawberry hill station" },
  { name: "Shirdi", state: "Maharashtra", shortDescription: "Sai Baba pilgrimage center" },
  { name: "Kolhapur", state: "Maharashtra", shortDescription: "Royal city with Mahalaxmi Temple" },
  { name: "Ajanta", state: "Maharashtra", shortDescription: "UNESCO Buddhist cave paintings" },
  { name: "Ellora", state: "Maharashtra", shortDescription: "UNESCO rock-cut cave temples" },
  { name: "Matheran", state: "Maharashtra", shortDescription: "Asia's only automobile-free hill station" },
  { name: "Alibaug", state: "Maharashtra", shortDescription: "Beach getaway from Mumbai" },
  { name: "Ganpatipule", state: "Maharashtra", shortDescription: "Beach town with Ganesh temple" },
  { name: "Panchgani", state: "Maharashtra", shortDescription: "Table Land hill station" },
  { name: "Lavasa", state: "Maharashtra", shortDescription: "Planned hill city near Pune" },
  { name: "Ratnagiri", state: "Maharashtra", shortDescription: "Alphonso mango capital and beaches" },
  { name: "Tarkarli", state: "Maharashtra", shortDescription: "Scuba diving and beach destination" },
  { name: "Tadoba", state: "Maharashtra", shortDescription: "Tiger reserve in Vidarbha" },
  { name: "Konkan", state: "Maharashtra", shortDescription: "Coastal paradise with pristine beaches" },
  { name: "Bhandardara", state: "Maharashtra", shortDescription: "Lake surrounded by Sahyadri hills" },
  { name: "Khandala", state: "Maharashtra", shortDescription: "Twin hill station of Lonavala" },
  { name: "Igatpuri", state: "Maharashtra", shortDescription: "Vipassana center and trekking" },
  
  // MANIPUR
  { name: "Imphal", state: "Manipur", shortDescription: "Capital with Kangla Fort and Ima Keithel" },
  { name: "Loktak Lake", state: "Manipur", shortDescription: "Floating islands and Keibul Lamjao" },
  { name: "Moirang", state: "Manipur", shortDescription: "INA memorial and Loktak nearby" },
  { name: "Ukhrul", state: "Manipur", shortDescription: "Land of Shirui lily flower" },
  { name: "Churachandpur", state: "Manipur", shortDescription: "Hill district with tribal culture" },
  
  // MEGHALAYA
  { name: "Shillong", state: "Meghalaya", shortDescription: "Scotland of the East with waterfalls" },
  { name: "Cherrapunji", state: "Meghalaya", shortDescription: "Wettest place on Earth with living root bridges" },
  { name: "Mawlynnong", state: "Meghalaya", shortDescription: "Cleanest village in Asia" },
  { name: "Dawki", state: "Meghalaya", shortDescription: "Crystal clear Umngot River" },
  { name: "Mawsynram", state: "Meghalaya", shortDescription: "Highest rainfall place with caves" },
  { name: "Nongriat", state: "Meghalaya", shortDescription: "Double decker living root bridge" },
  { name: "Tura", state: "Meghalaya", shortDescription: "Gateway to Nokrek National Park" },
  { name: "Jowai", state: "Meghalaya", shortDescription: "Krang Suri waterfall nearby" },
  
  // MIZORAM
  { name: "Aizawl", state: "Mizoram", shortDescription: "Hill capital with unique culture" },
  { name: "Lunglei", state: "Mizoram", shortDescription: "Second largest town with scenic beauty" },
  { name: "Champhai", state: "Mizoram", shortDescription: "Rice bowl of Mizoram near Myanmar" },
  { name: "Reiek", state: "Mizoram", shortDescription: "Mountain peak with heritage village" },
  { name: "Phawngpui", state: "Mizoram", shortDescription: "Blue Mountain highest peak" },
  
  // NAGALAND
  { name: "Kohima", state: "Nagaland", shortDescription: "WWII memorial and Hornbill festival" },
  { name: "Dimapur", state: "Nagaland", shortDescription: "Commercial hub with Kachari ruins" },
  { name: "Mokokchung", state: "Nagaland", shortDescription: "Ao Naga cultural center" },
  { name: "Khonoma", state: "Nagaland", shortDescription: "Green village with warrior history" },
  { name: "Dzukou Valley", state: "Nagaland", shortDescription: "Valley of flowers trek" },
  
  // ODISHA
  { name: "Bhubaneswar", state: "Odisha", shortDescription: "Temple City with ancient architecture" },
  { name: "Puri", state: "Odisha", shortDescription: "Sacred Jagannath Temple and beach" },
  { name: "Konark", state: "Odisha", shortDescription: "UNESCO Sun Temple masterpiece" },
  { name: "Cuttack", state: "Odisha", shortDescription: "Silver city with Barabati Fort" },
  { name: "Chilika Lake", state: "Odisha", shortDescription: "Asia's largest brackish water lagoon" },
  { name: "Gopalpur", state: "Odisha", shortDescription: "Beach resort with lighthouse" },
  { name: "Simlipal", state: "Odisha", shortDescription: "Tiger reserve with waterfalls" },
  { name: "Sambalpur", state: "Odisha", shortDescription: "Hirakud Dam and handlooms" },
  { name: "Bhitarkanika", state: "Odisha", shortDescription: "Mangrove and crocodile sanctuary" },
  { name: "Chandipur", state: "Odisha", shortDescription: "Hide and seek beach" },
  { name: "Daringbadi", state: "Odisha", shortDescription: "Kashmir of Odisha hill station" },
  
  // PUNJAB
  { name: "Amritsar", state: "Punjab", shortDescription: "Golden Temple and Wagah Border" },
  { name: "Ludhiana", state: "Punjab", shortDescription: "Manchester of India textile hub" },
  { name: "Jalandhar", state: "Punjab", shortDescription: "Sports goods manufacturing center" },
  { name: "Patiala", state: "Punjab", shortDescription: "Royal city with Qila Mubarak" },
  { name: "Bathinda", state: "Punjab", shortDescription: "Ancient fort city" },
  { name: "Mohali", state: "Punjab", shortDescription: "IT city with cricket stadium" },
  { name: "Kapurthala", state: "Punjab", shortDescription: "City of palaces and gardens" },
  { name: "Anandpur Sahib", state: "Punjab", shortDescription: "Sikh holy city birthplace of Khalsa" },
  
  // RAJASTHAN
  { name: "Udaipur", state: "Rajasthan", shortDescription: "City of Lakes with romantic palaces" },
  { name: "Jodhpur", state: "Rajasthan", shortDescription: "Blue City with Mehrangarh Fort" },
  { name: "Jaisalmer", state: "Rajasthan", shortDescription: "Golden City with desert safari" },
  { name: "Pushkar", state: "Rajasthan", shortDescription: "Sacred lake and camel fair" },
  { name: "Mount Abu", state: "Rajasthan", shortDescription: "Only hill station in Rajasthan" },
  { name: "Bikaner", state: "Rajasthan", shortDescription: "Camel country with Junagarh Fort" },
  { name: "Ajmer", state: "Rajasthan", shortDescription: "Sufi shrine of Khwaja Sahib" },
  { name: "Ranthambore", state: "Rajasthan", shortDescription: "Tiger reserve with ancient fort" },
  { name: "Chittorgarh", state: "Rajasthan", shortDescription: "Largest fort in India" },
  { name: "Bundi", state: "Rajasthan", shortDescription: "Step wells and blue houses" },
  { name: "Kumbhalgarh", state: "Rajasthan", shortDescription: "Great Wall of India fort" },
  { name: "Alwar", state: "Rajasthan", shortDescription: "Gateway to Sariska Tiger Reserve" },
  { name: "Bharatpur", state: "Rajasthan", shortDescription: "Keoladeo bird sanctuary UNESCO" },
  { name: "Sawai Madhopur", state: "Rajasthan", shortDescription: "Gateway to Ranthambore" },
  { name: "Shekhawati", state: "Rajasthan", shortDescription: "Open art gallery with havelis" },
  { name: "Mandawa", state: "Rajasthan", shortDescription: "Painted town of Shekhawati" },
  { name: "Ranakpur", state: "Rajasthan", shortDescription: "Intricate Jain temple complex" },
  
  // SIKKIM
  { name: "Gangtok", state: "Sikkim", shortDescription: "Capital with monasteries and Kanchenjunga views" },
  { name: "Pelling", state: "Sikkim", shortDescription: "Kanchenjunga viewpoint and monasteries" },
  { name: "Lachen", state: "Sikkim", shortDescription: "Gateway to Gurudongmar Lake" },
  { name: "Lachung", state: "Sikkim", shortDescription: "Gateway to Yumthang Valley" },
  { name: "Yumthang Valley", state: "Sikkim", shortDescription: "Valley of flowers in North Sikkim" },
  { name: "Tsomgo Lake", state: "Sikkim", shortDescription: "Sacred glacial lake on Indo-China border" },
  { name: "Nathula Pass", state: "Sikkim", shortDescription: "Indo-China border pass" },
  { name: "Ravangla", state: "Sikkim", shortDescription: "Buddha Park with giant statue" },
  { name: "Namchi", state: "Sikkim", shortDescription: "Religious site with Char Dham" },
  { name: "Zuluk", state: "Sikkim", shortDescription: "Silk route with zigzag roads" },
  { name: "Gurudongmar Lake", state: "Sikkim", shortDescription: "Sacred high altitude lake" },
  
  // TAMIL NADU
  { name: "Chennai", state: "Tamil Nadu", shortDescription: "Cultural capital with Marina Beach" },
  { name: "Madurai", state: "Tamil Nadu", shortDescription: "Temple city with Meenakshi Temple" },
  { name: "Coimbatore", state: "Tamil Nadu", shortDescription: "Manchester of South India" },
  { name: "Tiruchirappalli", state: "Tamil Nadu", shortDescription: "Rock Fort Temple city" },
  { name: "Ooty", state: "Tamil Nadu", shortDescription: "Queen of Nilgiris hill stations" },
  { name: "Kodaikanal", state: "Tamil Nadu", shortDescription: "Princess of Hill Stations" },
  { name: "Mahabalipuram", state: "Tamil Nadu", shortDescription: "UNESCO shore temples" },
  { name: "Pondicherry", state: "Tamil Nadu", shortDescription: "French colonial heritage town" },
  { name: "Kanyakumari", state: "Tamil Nadu", shortDescription: "Southernmost tip of India" },
  { name: "Thanjavur", state: "Tamil Nadu", shortDescription: "UNESCO Brihadeeswara Temple" },
  { name: "Rameswaram", state: "Tamil Nadu", shortDescription: "Sacred island pilgrimage" },
  { name: "Coonoor", state: "Tamil Nadu", shortDescription: "Tea estates in Nilgiris" },
  { name: "Yelagiri", state: "Tamil Nadu", shortDescription: "Offbeat hill station" },
  { name: "Yercaud", state: "Tamil Nadu", shortDescription: "Jewel of South with lake" },
  { name: "Dhanushkodi", state: "Tamil Nadu", shortDescription: "Ghost town on India's tip" },
  { name: "Valparai", state: "Tamil Nadu", shortDescription: "Tea estate hill station" },
  { name: "Kumbakonam", state: "Tamil Nadu", shortDescription: "Temple town with Mahamaham" },
  { name: "Chidambaram", state: "Tamil Nadu", shortDescription: "Nataraja Temple of cosmic dance" },
  { name: "Salem", state: "Tamil Nadu", shortDescription: "Steel city with Yercaud nearby" },
  { name: "Tirunelveli", state: "Tamil Nadu", shortDescription: "Ancient temple town" },
  
  // TELANGANA
  { name: "Warangal", state: "Telangana", shortDescription: "Kakatiya kingdom heritage" },
  { name: "Nizamabad", state: "Telangana", shortDescription: "Historic forts and temples" },
  { name: "Karimnagar", state: "Telangana", shortDescription: "Silver filigree work center" },
  { name: "Khammam", state: "Telangana", shortDescription: "Tribal culture and forests" },
  { name: "Nagarjunasagar", state: "Telangana", shortDescription: "Dam and Buddhist ruins" },
  { name: "Ramoji Film City", state: "Telangana", shortDescription: "World's largest film studio complex" },
  
  // TRIPURA
  { name: "Agartala", state: "Tripura", shortDescription: "Capital with Ujjayanta Palace" },
  { name: "Udaipur", state: "Tripura", shortDescription: "Lake town with Tripura Sundari Temple" },
  { name: "Neermahal", state: "Tripura", shortDescription: "Water palace in Rudrasagar Lake" },
  { name: "Unakoti", state: "Tripura", shortDescription: "Rock carvings pilgrimage site" },
  { name: "Jampui Hills", state: "Tripura", shortDescription: "Orange festival location" },
  
  // UTTAR PRADESH
  { name: "Varanasi", state: "Uttar Pradesh", shortDescription: "Spiritual capital on sacred Ganges" },
  { name: "Agra", state: "Uttar Pradesh", shortDescription: "Home to iconic Taj Mahal" },
  { name: "Lucknow", state: "Uttar Pradesh", shortDescription: "City of Nawabs with rich culture" },
  { name: "Prayagraj", state: "Uttar Pradesh", shortDescription: "Confluence of three rivers and Kumbh Mela" },
  { name: "Mathura", state: "Uttar Pradesh", shortDescription: "Birthplace of Lord Krishna" },
  { name: "Vrindavan", state: "Uttar Pradesh", shortDescription: "Sacred town of Radha-Krishna" },
  { name: "Ayodhya", state: "Uttar Pradesh", shortDescription: "Birthplace of Lord Rama" },
  { name: "Fatehpur Sikri", state: "Uttar Pradesh", shortDescription: "UNESCO Mughal ghost city" },
  { name: "Sarnath", state: "Uttar Pradesh", shortDescription: "Where Buddha gave first sermon" },
  { name: "Chitrakoot", state: "Uttar Pradesh", shortDescription: "Rama's exile spot with temples" },
  { name: "Noida", state: "Uttar Pradesh", shortDescription: "NCR city with modern infrastructure" },
  { name: "Greater Noida", state: "Uttar Pradesh", shortDescription: "Formula 1 circuit and expo city" },
  { name: "Ghaziabad", state: "Uttar Pradesh", shortDescription: "Gateway to UP from Delhi" },
  { name: "Kanpur", state: "Uttar Pradesh", shortDescription: "Industrial city with leather industry" },
  { name: "Jhansi", state: "Uttar Pradesh", shortDescription: "Fort city of Rani Lakshmibai" },
  { name: "Aligarh", state: "Uttar Pradesh", shortDescription: "Lock industry and university town" },
  { name: "Meerut", state: "Uttar Pradesh", shortDescription: "Sports goods and 1857 mutiny" },
  { name: "Gorakhpur", state: "Uttar Pradesh", shortDescription: "Gateway to Nepal" },
  { name: "Kushinagar", state: "Uttar Pradesh", shortDescription: "Where Buddha attained Mahaparinirvana" },
  
  // UTTARAKHAND
  { name: "Rishikesh", state: "Uttarakhand", shortDescription: "Yoga capital and adventure hub" },
  { name: "Haridwar", state: "Uttarakhand", shortDescription: "Gateway to Char Dham and Ganga Aarti" },
  { name: "Dehradun", state: "Uttarakhand", shortDescription: "Capital city in Doon Valley" },
  { name: "Nainital", state: "Uttarakhand", shortDescription: "Lake district hill station" },
  { name: "Mussoorie", state: "Uttarakhand", shortDescription: "Queen of Hills near Dehradun" },
  { name: "Jim Corbett", state: "Uttarakhand", shortDescription: "India's first tiger reserve" },
  { name: "Auli", state: "Uttarakhand", shortDescription: "Skiing destination with Himalayan views" },
  { name: "Valley of Flowers", state: "Uttarakhand", shortDescription: "UNESCO alpine flowers sanctuary" },
  { name: "Kedarnath", state: "Uttarakhand", shortDescription: "Sacred Jyotirlinga in Himalayas" },
  { name: "Badrinath", state: "Uttarakhand", shortDescription: "Sacred Char Dham pilgrimage" },
  { name: "Gangotri", state: "Uttarakhand", shortDescription: "Source of River Ganga" },
  { name: "Yamunotri", state: "Uttarakhand", shortDescription: "Source of River Yamuna" },
  { name: "Almora", state: "Uttarakhand", shortDescription: "Cultural hub of Kumaon hills" },
  { name: "Ranikhet", state: "Uttarakhand", shortDescription: "Queen's meadow hill station" },
  { name: "Bhimtal", state: "Uttarakhand", shortDescription: "Largest lake in Kumaon" },
  { name: "Lansdowne", state: "Uttarakhand", shortDescription: "Quiet cantonment hill station" },
  { name: "Chopta", state: "Uttarakhand", shortDescription: "Mini Switzerland with Tungnath" },
  { name: "Binsar", state: "Uttarakhand", shortDescription: "Wildlife sanctuary with Himalayan views" },
  { name: "Mukteshwar", state: "Uttarakhand", shortDescription: "Cliff hanging temple with views" },
  { name: "Kausani", state: "Uttarakhand", shortDescription: "Tea gardens with Himalayan panorama" },
  { name: "Chakrata", state: "Uttarakhand", shortDescription: "Offbeat hill station with Tiger Falls" },
  
  // WEST BENGAL
  { name: "Kolkata", state: "West Bengal", shortDescription: "City of Joy with colonial heritage" },
  { name: "Darjeeling", state: "West Bengal", shortDescription: "Queen of Hills with tea gardens" },
  { name: "Siliguri", state: "West Bengal", shortDescription: "Gateway to Northeast and Darjeeling" },
  { name: "Kalimpong", state: "West Bengal", shortDescription: "Hill town with Buddhist monasteries" },
  { name: "Sundarbans", state: "West Bengal", shortDescription: "UNESCO mangrove with Royal Bengal Tigers" },
  { name: "Shantiniketan", state: "West Bengal", shortDescription: "Tagore's university and art" },
  { name: "Digha", state: "West Bengal", shortDescription: "Popular beach near Kolkata" },
  { name: "Murshidabad", state: "West Bengal", shortDescription: "Nawabi heritage city" },
  { name: "Bishnupur", state: "West Bengal", shortDescription: "Terracotta temples UNESCO" },
  { name: "Kurseong", state: "West Bengal", shortDescription: "Land of white orchids" },
  { name: "Mirik", state: "West Bengal", shortDescription: "Lake surrounded by tea gardens" },
  { name: "Lava", state: "West Bengal", shortDescription: "Kanchenjunga views and forest" },
  { name: "Sandakphu", state: "West Bengal", shortDescription: "Highest peak with four 8000m peaks view" },
  { name: "Mandarmani", state: "West Bengal", shortDescription: "Beach with longest driveable stretch" },
  { name: "Bakkhali", state: "West Bengal", shortDescription: "Quiet beach destination" },
  
  // UNION TERRITORIES
  { name: "Delhi", state: "Delhi", shortDescription: "Capital city with monuments and modernity" },
  { name: "New Delhi", state: "Delhi", shortDescription: "Lutyens' Delhi with government buildings" },
  { name: "Old Delhi", state: "Delhi", shortDescription: "Mughal heritage and street food" },
  { name: "Connaught Place", state: "Delhi", shortDescription: "Central business district" },
  { name: "Hauz Khas", state: "Delhi", shortDescription: "Historic complex with urban village" },
  { name: "Mehrauli", state: "Delhi", shortDescription: "Qutub Minar and archaeological park" },
  
  { name: "Port Blair", state: "Andaman & Nicobar", shortDescription: "Capital with Cellular Jail" },
  { name: "Havelock Island", state: "Andaman & Nicobar", shortDescription: "Radhanagar Beach paradise" },
  { name: "Neil Island", state: "Andaman & Nicobar", shortDescription: "Natural bridge and beaches" },
  { name: "Ross Island", state: "Andaman & Nicobar", shortDescription: "British era ruins" },
  { name: "Baratang", state: "Andaman & Nicobar", shortDescription: "Limestone caves and mangroves" },
  
  { name: "Puducherry", state: "Puducherry", shortDescription: "French colonial charm and beaches" },
  { name: "Auroville", state: "Puducherry", shortDescription: "Experimental universal township" },
  { name: "Paradise Beach", state: "Puducherry", shortDescription: "Secluded beach by boat" },
  
  { name: "Daman", state: "Dadra and Nagar Haveli and Daman and Diu", shortDescription: "Portuguese heritage and beaches" },
  { name: "Silvassa", state: "Dadra and Nagar Haveli and Daman and Diu", shortDescription: "Capital with tribal culture" },
  
  { name: "Kavaratti", state: "Lakshadweep", shortDescription: "Capital island with lagoons" },
  { name: "Agatti", state: "Lakshadweep", shortDescription: "Airport island with coral reefs" },
  { name: "Bangaram", state: "Lakshadweep", shortDescription: "Uninhabited island resort" },
  { name: "Minicoy", state: "Lakshadweep", shortDescription: "Lighthouse and Maldivian culture" },
  
  { name: "Srinagar", state: "Jammu & Kashmir", shortDescription: "Dal Lake houseboats and gardens" },
  { name: "Gulmarg", state: "Jammu & Kashmir", shortDescription: "Skiing and world's highest gondola" },
  { name: "Pahalgam", state: "Jammu & Kashmir", shortDescription: "Valley of Shepherds and Amarnath base" },
  { name: "Sonmarg", state: "Jammu & Kashmir", shortDescription: "Meadow of Gold with Thajiwas Glacier" },
  { name: "Jammu", state: "Jammu & Kashmir", shortDescription: "City of Temples and Vaishno Devi base" },
  { name: "Patnitop", state: "Jammu & Kashmir", shortDescription: "Hill station between Jammu-Srinagar" },
  { name: "Vaishno Devi", state: "Jammu & Kashmir", shortDescription: "Sacred shrine in Trikuta Hills" },
  { name: "Doodhpathri", state: "Jammu & Kashmir", shortDescription: "Valley of Milk meadows" },
  { name: "Yusmarg", state: "Jammu & Kashmir", shortDescription: "Meadow of Jesus with pine forests" },
  { name: "Betaab Valley", state: "Jammu & Kashmir", shortDescription: "Bollywood film location valley" },
];

async function seedDestinations() {
  console.log("Seeding destinations...");
  
  try {
    const existing = await storage.getAllDestinations();
    if (existing.length > 0) {
      console.log(`Found ${existing.length} existing destinations, skipping seed.`);
      return;
    }

    for (const destination of destinationsData) {
      await storage.createDestination(destination);
    }
    
    console.log(`Successfully seeded ${destinationsData.length} destinations!`);
  } catch (error) {
    console.error("Error seeding destinations:", error);
    throw error;
  }
}

export { seedDestinations };
